version: "{build}"
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
nuget:
  disable_publish_on_pr: true
build_script:
  - ps: .\build.ps1
test: off
artifacts:
  - path: .\artifacts\**\*.nupkg
    name: NuGet
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/eshva-public/api/v2/package
    api_key:
      secure: EWEbUVHovEaxui62fk5XtNTctmLzY5NHj8gqY+7s/eRl5zqIxPzwVUVspbJrU/TP
    skip_symbols: true
    on:
      branch: master
  - provider: NuGet
    name: production
    skip_symbols: true
    api_key:
      secure: X0KFzlh5UoQWKhbg80RuvGqVPSDHMUm23F+BRBnonaGUZ6dMbKqedRjXXKHF7Tgn
    on:
      appveyor_repo_tag: true
